name: ADF Published Trigger
on:
  push:
    branches:
    - adf_publish

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Print message
      run: echo "ADF was published in the Azure Portal"
